### ISSUE TITLE
Reuse NetworkingManager

### ISSUE THREAD

**Issue by Minoru** [Minoru/AI-simulator-SDK#1]
To send a message, example bot creates ad-hoc `NetworkingManager` instance, but that's not the way it should be.  The main problem with such an approach is that you can't receive messages if you don't have "persistent" instance that is present during whole bot's lifecycle.

Please take care of refactoring example bot. I will no longer develop it as my actual work is developing and maintaining SDK itself.

**Comment by SmirnoffYM** [comment]
Yes, i know it. I'll <del>transmit this information to Vladimir</del> solve the problem at this week.

**Comment by SmirnoffYM** [comment]
I hope singleton resolved this problem.

**Comment by Minoru** [comment]
No, it didn't. I don't want to enforce any usage patterns, so you should not have changed NetworkingManager.{cpp,h}.

Please resolve the problem in the bot itself.

**Comment by SmirnoffYM** [comment]
Huh, but why? Can you substantiate why using singleton is bad in our case?

**Comment by Minoru** [comment]
Summary: we resolved that SDK shouldn't enforce any usage patterns, it should only provide `NetworkingManager` class. I reverted changes that introduced singleton pattern in 86055fa.
