### ISSUE TITLE
Network protocol

### ISSUE THREAD

**Issue by SmirnoffYM** [Minoru/AI-simulator-SDK#2]
First of all, we must move [this](https://github.com/SmirnoffYM/AI-simulator/wiki/Network-protocol) page from AI-simulator wiki to AI-simulator-SDK wiki. Next, we must replace qjson protocol by new binary in that page. Finally, we must create messages like "Start" (with robot parameters), "Pause" and "Stop" and implement them.

**Comment by Minoru** [comment]
I agree with the latter two points, but not with the first one. Protocol should be documented in simulator's wiki because it's part ot the simulator, while SDK is just an implementation of it.

I'll take care of the second and protocol part of the third points tonight or tomorrow.

**Comment by SmirnoffYM** [comment]
Hmm, do you propose to leave SDK wiki always empty?

**Comment by Minoru** [comment]
Yes, until there's something to put in there.

**Comment by SmirnoffYM** [comment]
Okay

**Comment by Minoru** [comment]
As no part of this issue touches SDK, I'm closing it. [I moved the part about `Start`, `Stop` and`Pause` messages to AI-simulator issue tracker](https://github.com/SmirnoffYM/AI-simulator/issues/12).
