### ISSUE TITLE
Merge constants.h from robot and environment projects

### ISSUE THREAD

**Issue by SmirnoffYM** [Minoru/AI-simulator-SDK#3]
It seems that constant.h files contains similar information and it will be logical to keep this information in one file used by both projects.

**Comment by Minoru** [comment]
Do you see any way to achieve that? Because I don't.

**Comment by SmirnoffYM** [comment]
Merge both files, move resulting constants.h to root directory of the repository and add it to the .pro files of the both projects.

**Comment by Minoru** [comment]
> move resulting constants.h to root directory of the repository

Which one: main or -SDK?

> add it to the .pro files of the both projects

If we remove the file from one of the projects, we would no longer be able to build it. If we keep the file in both projects, it would make synchronization difficult and we won't gain anything other than headache.

**Comment by SmirnoffYM** [comment]
> Which one: main or -SDK?

SDK

> If we remove the file from one of the projects, we would no longer be able to build it. If we keep the file in both projects, it would make synchronization difficult and we won't gain anything other than headache.

You didn't understand. I propose to make like with NetworkingManager class. Common file for two projects.

**Comment by Minoru** [comment]
Oh, I see now. I have no problem with that; you're free to act as you described in the previous comment.
