### ISSUE TITLE
Return values of some helper functions

### ISSUE THREAD

**Issue by Minoru** [Minoru/AI-simulator-SDK#6]
As we all know, some messages would result in answers from the simulator. The question is, how to represent that in the high-level abstraction we're building in `example/robot/robot.cpp`? I see two approaches:
- hide _all_ network specifics and make helper functions to wait for answer and then return it. Pros: encapsulation. Cons: network is slow, so those helpers would be slow too - users may not expect that.
- create separate set of helpers that would retrieve answers. Pros: some helpers would be fast (those that retrieve answers are still slow). Cons: no encapsulation; user may implement something I described in the previous option.

I would prefer the first approach, but would like to hear your feedback.

**Comment by SmirnoffYM** [comment]
> hide all network specifics and make helper functions to wait for answer and then return it

this one

**Comment by Minoru** [comment]
As far as I can tell, I ended up going with your suggestion and started implementing the option mentioned (cf. cbe6805e007e43c35e1d13bfcccd410b5a2f0686). I'm closing the issue.
